<?php

use Illuminate\Database\Seeder;

class tabel_pegawais_seed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pegawais')->insert([
            ["id"=>"0f9545af-d6d9-44bd-9df9-cddabca91005",
                "jk_id"=>2,
                "desa_id"=>null,
                "jabatan_id"=>"1",
                "nama"=>"manager",
                "cita_cita"=>null,
                "cv"=>"useruploads/image/pegawai/cv/CV-admin-110718204657-1.jpg",
                "no_hp"=>"087676675657",
                "agama"=>null,
                "alamat"=>"alamat",
                "no_ktp"=>null,
                "nik"=>"aaaaa",
                "mulai_bekerja"=>null,
                "tempat_lahir"=>"sukabumi",
                "tanggal_lahir"=>"2018-7-11",
                "path_foto_person"=>"useruploads/image/pegawai/person/personal-admin-150718145002-0f9545af-d6d9-44bd-9df9-cddabca91005.gif",
                "path_foto_ktp"=>null,
                "path_foto_kk"=>null,
                "is_active"=>1,
                "tanggal_keluar"=>null,
                "alasan_keluar"=>null,
                "email"=>"manager@wi.com",
                "username"=>"manager",
                "password"=>bcrypt('admin'),
                "disetujui_1"=>null,
                "disetujui_1_id"=>null,
                "tanggal_disetujui_1"=>null,
                "alasan_disetujui_1"=>null,
                "remember_token"=>"tTlLDCAmZ3tVnZKCIEzuFLM9X1QVJM3HgVf28xfVgd2AAAMlFzYCD1fF4xHU",
                "created_by"=>null,
                "updated_by"=>null,
                "deleted_by"=>null,
            ],
            [
                "id"=>"b123c193-c48f-4da0-b94d-f4ef1b2687bf",
                "jk_id"=>1,
                "desa_id"=>null,
                "jabatan_id"=>"2",
                "nama"=>"heru sugiarto",
                "cita_cita"=>null,
                "cv"=>"useruploads/image/pegawai/cv/CV-nama-140718131556-1.docx",
                "no_hp"=>"08568987979",
                "agama"=>null,
                "alamat"=>"kp salajambe no 20 xyz",
                "no_ktp"=>null,
                "nik"=>"09-232",
                "mulai_bekerja"=>null,
                "tempat_lahir"=>"sukabumi",
                "tanggal_lahir"=>"1990-2-6",
                "path_foto_person"=>"useruploads/image/pegawai/person/personal-nama-140718131556-1.jpg",
                "path_foto_ktp"=>null,
                "path_foto_kk"=>null,
                "is_active"=>1,
                "tanggal_keluar"=>null,
                "alasan_keluar"=>null,
                "email"=>"staf@wi.com",
                "username"=>"staf",
                "password"=>bcrypt('admin'),
                "disetujui_1"=>null,
                "disetujui_1_id"=>null,
                "tanggal_disetujui_1"=>null,
                "alasan_disetujui_1"=>null,
                "remember_token"=>null,
                "created_by"=>null,
                "updated_by"=>null,
                "deleted_by"=>null,
            ],
            [
                "id"=>"e555c492-7922-421d-b6da-1f1ac9cae7df",
                "jk_id"=>1,
                "desa_id"=>null,
                "jabatan_id"=>"3",
                "nama"=>"admirahmani",
                "cita_cita"=>null,
                "cv"=>"useruploads/image/pegawai/cv/CV-user 3-140718131805-1.gif",
                "no_hp"=>"0866565757",
                "agama"=>null,
                "alamat"=>"jl margonda raya",
                "no_ktp"=>null,
                "nik"=>"09098",
                "mulai_bekerja"=>null,
                "tempat_lahir"=>"sukabumi",
                "tanggal_lahir"=>"1980-6-24",
                "path_foto_person"=>"useruploads/image/pegawai/person/personal-user 3-140718131805-1.jpg",
                "path_foto_ktp"=>null,
                "path_foto_kk"=>null,
                "is_active"=>1,
                "tanggal_keluar"=>null,
                "alasan_keluar"=>null,
                "email"=>"admin@wi.com",
                "username"=>"admin",
                "password"=>bcrypt('admin'),
                "disetujui_1"=>null,
                "disetujui_1_id"=>null,
                "tanggal_disetujui_1"=>null,
                "alasan_disetujui_1"=>null,
                "remember_token"=>null,
                "created_by"=>null,
                "updated_by"=>null,
                "deleted_by"=>null,
                 
            ]
        ]);
    }
}
